# Generated by Django 5.2.4 on 2025-08-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('notes', 'Notes'), ('pyqs', 'Previous Year Questions'), ('books', 'Books')], default='notes', max_length=10)),
                ('department', models.CharField(choices=[('cse', 'Computer Science and Engineering'), ('it', 'Information Technology'), ('ece', 'Electronics and Communication Engineering'), ('mech', 'Mechanical Engineering'), ('civil', 'Civil Engineering'), ('chem', 'Chemical Engineering'), ('bt', 'Biotechnology'), ('math', 'Mathematics'), ('phy', 'Physics'), ('chemistry', 'Chemistry')], max_length=10)),
                ('year', models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year')], max_length=1)),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_code', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='academic_resources/')),
                ('external_link', models.URLField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
